# Generated by Django 5.0.1 on 2024-02-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('image_description', models.CharField(max_length=255)),
                ('image_date', models.DateTimeField(verbose_name='date published')),
                ('image_tags', models.CharField(max_length=255)),
                ('image_size', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('image_width', models.IntegerField()),
            ],
        ),
    ]
