# Generated by Django 5.0.2 on 2024-02-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DallEImage',
            fields=[
                ('image', models.ImageField(upload_to='media/')),
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_prompt', models.CharField(max_length=255)),
                ('image_date', models.DateTimeField(verbose_name='date published')),
                ('image_model', models.CharField(choices=[('dall-e-2', 'dall-e-2'), ('dall-e-3', 'dall-e-3')], max_length=10)),
                ('image_quality', models.CharField(choices=[('hd', 'hd'), ('standard', 'standard')], max_length=10)),
                ('image_style', models.CharField(choices=[('vivid', 'vivid'), ('natural', 'natural')], max_length=10)),
                ('image_user', models.CharField(max_length=255)),
                ('image_size', models.CharField(choices=[('256x256', '256x256'), ('512x512', '512x512'), ('1024x1024', '1024x1024'), ('1024x1792', '1024x1792'), ('1792x1024', '1792x1024')], max_length=10)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
