# Generated by Django 5.0.2 on 2024-02-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_dalleimage_image_tags_alter_dalleimage_image_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dalleimage',
            name='image_model',
            field=models.CharField(choices=[('dall-e-2', 'dall-e-2'), ('dall-e-3', 'dall-e-3')], max_length=255),
        ),
        migrations.AlterField(
            model_name='dalleimage',
            name='image_quality',
            field=models.CharField(choices=[('hd', 'hd'), ('standard', 'standard')], max_length=255),
        ),
        migrations.AlterField(
            model_name='dalleimage',
            name='image_size',
            field=models.CharField(choices=[('256x256', '256x256'), ('512x512', '512x512'), ('1024x1024', '1024x1024'), ('1024x1792', '1024x1792'), ('1792x1024', '1792x1024')], max_length=255),
        ),
        migrations.AlterField(
            model_name='dalleimage',
            name='image_style',
            field=models.CharField(choices=[('vivid', 'vivid'), ('natural', 'natural')], max_length=255),
        ),
    ]
